[package]
name = "twitter-bulk-media-upload"
version = "0.1.0"
authors = ["Alpha Shuro <alphashuro@gmail.com>"]

[dependencies]
reqwest = "0.8.5"
serde = "*"
serde_derive = "*"
serde_json = "*"
dotenv = "*"
dotenv_codegen = "*"