kind: Service
apiVersion: v1
metadata:
  name: media-prod-lb
  labels:
    env: production
    name: media
    project: bluerobot
spec:
  selector:
    env: production
    name: media
    project: bluerobot
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer

